// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using erMarket_varastonhallinta_Dal.Dao;

namespace erMarket_varastonhallinta_Dal.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("erMarket_varastonhallinta_Dal.Dao.DaoCategories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategorysId")
                        .HasColumnType("int");

                    b.Property<string>("CategorysName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("erMarket_varastonhallinta_Dal.Dao.DaoProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DaoStoreId")
                        .HasColumnType("int");

                    b.Property<int>("InStock")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("QuantityChanged")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DaoStoreId");

                    b.ToTable("DaoProduct");
                });

            modelBuilder.Entity("erMarket_varastonhallinta_Dal.Dao.DaoProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategorysId")
                        .HasColumnType("int");

                    b.Property<string>("CategorysName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DaoProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DaoProductId");

                    b.ToTable("DaoProductCategory");
                });

            modelBuilder.Entity("erMarket_varastonhallinta_Dal.Dao.DaoStore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StoresId")
                        .HasColumnType("int");

                    b.Property<string>("Supervisor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("erMarket_varastonhallinta_Dal.Dao.DaoProduct", b =>
                {
                    b.HasOne("erMarket_varastonhallinta_Dal.Dao.DaoStore", null)
                        .WithMany("Products")
                        .HasForeignKey("DaoStoreId");
                });

            modelBuilder.Entity("erMarket_varastonhallinta_Dal.Dao.DaoProductCategory", b =>
                {
                    b.HasOne("erMarket_varastonhallinta_Dal.Dao.DaoProduct", null)
                        .WithMany("Categories")
                        .HasForeignKey("DaoProductId");
                });
#pragma warning restore 612, 618
        }
    }
}
